apiVersion: apps/v1
kind: Deployment
metadata:
  name: kgs-deployment
  labels:
    app: kgs
spec:
  selector:
    matchLabels:
      app: kgs
  replicas: 1
  template:
    metadata:
      labels:
        app: kgs
    spec:
      containers:
        - name: kgs
          image:
          ports:
            - name: kgs-service
              containerPort: 50052

---
apiVersion: v1
kind: Service
metadata:
  name: kgs-service
spec:
  selector:
    app: kgs
  ports:
    - port: 50052
      targetPort: kgs-service