apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-main-deployment
  labels:
    app: redis-main
spec:
  selector:
    matchLabels:
      app: redis-main
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-main
    spec:
      containers:
        - name: redis-main
          image: redis 
          ports:
            - name: redismain
              containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: redis-main-service
spec:
  selector:
    app: redis-main
  ports:
    - port: 6379
      targetPort: 6379