// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kgs.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type KGSRequest struct {
	Request              string   `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KGSRequest) Reset()         { *m = KGSRequest{} }
func (m *KGSRequest) String() string { return proto.CompactTextString(m) }
func (*KGSRequest) ProtoMessage()    {}
func (*KGSRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef3b694081b765dd, []int{0}
}

func (m *KGSRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KGSRequest.Unmarshal(m, b)
}
func (m *KGSRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KGSRequest.Marshal(b, m, deterministic)
}
func (m *KGSRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KGSRequest.Merge(m, src)
}
func (m *KGSRequest) XXX_Size() int {
	return xxx_messageInfo_KGSRequest.Size(m)
}
func (m *KGSRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KGSRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KGSRequest proto.InternalMessageInfo

func (m *KGSRequest) GetRequest() string {
	if m != nil {
		return m.Request
	}
	return ""
}

type KGSResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KGSResponse) Reset()         { *m = KGSResponse{} }
func (m *KGSResponse) String() string { return proto.CompactTextString(m) }
func (*KGSResponse) ProtoMessage()    {}
func (*KGSResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef3b694081b765dd, []int{1}
}

func (m *KGSResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KGSResponse.Unmarshal(m, b)
}
func (m *KGSResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KGSResponse.Marshal(b, m, deterministic)
}
func (m *KGSResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KGSResponse.Merge(m, src)
}
func (m *KGSResponse) XXX_Size() int {
	return xxx_messageInfo_KGSResponse.Size(m)
}
func (m *KGSResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_KGSResponse.DiscardUnknown(m)
}

var xxx_messageInfo_KGSResponse proto.InternalMessageInfo

func (m *KGSResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*KGSRequest)(nil), "pb.KGSRequest")
	proto.RegisterType((*KGSResponse)(nil), "pb.KGSResponse")
}

func init() { proto.RegisterFile("kgs.proto", fileDescriptor_ef3b694081b765dd) }

var fileDescriptor_ef3b694081b765dd = []byte{
	// 146 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcc, 0x4e, 0x2f, 0xd6,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x52, 0xe3, 0xe2, 0xf2, 0x76, 0x0f,
	0x0e, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x92, 0xe0, 0x62, 0x2f, 0x82, 0x30, 0x25, 0x18,
	0x15, 0x18, 0x35, 0x38, 0x83, 0x60, 0x5c, 0x25, 0x55, 0x2e, 0x6e, 0xb0, 0xba, 0xe2, 0x82, 0xfc,
	0xbc, 0xe2, 0x54, 0x21, 0x31, 0x2e, 0xb6, 0xa2, 0xd4, 0xe2, 0xd2, 0x1c, 0x98, 0x3a, 0x28, 0xcf,
	0xc8, 0x19, 0x6c, 0x5c, 0x70, 0x6a, 0x51, 0x59, 0x66, 0x72, 0xaa, 0x90, 0x29, 0x97, 0x80, 0x7b,
	0x6a, 0x89, 0x5b, 0x51, 0x6a, 0xaa, 0x7b, 0x7e, 0x48, 0x66, 0x5e, 0x65, 0x68, 0x90, 0x8f, 0x10,
	0x9f, 0x5e, 0x41, 0x92, 0x1e, 0xc2, 0x4a, 0x29, 0x7e, 0x38, 0x1f, 0x62, 0xb4, 0x12, 0x43, 0x12,
	0x1b, 0xd8, 0x79, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x31, 0x75, 0x7a, 0x1e, 0xab, 0x00,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// KGSServiceClient is the client API for KGSService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type KGSServiceClient interface {
	GetFreeGoTinyURL(ctx context.Context, in *KGSRequest, opts ...grpc.CallOption) (*KGSResponse, error)
}

type kGSServiceClient struct {
	cc *grpc.ClientConn
}

func NewKGSServiceClient(cc *grpc.ClientConn) KGSServiceClient {
	return &kGSServiceClient{cc}
}

func (c *kGSServiceClient) GetFreeGoTinyURL(ctx context.Context, in *KGSRequest, opts ...grpc.CallOption) (*KGSResponse, error) {
	out := new(KGSResponse)
	err := c.cc.Invoke(ctx, "/pb.KGSService/GetFreeGoTinyURL", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KGSServiceServer is the server API for KGSService service.
type KGSServiceServer interface {
	GetFreeGoTinyURL(context.Context, *KGSRequest) (*KGSResponse, error)
}

// UnimplementedKGSServiceServer can be embedded to have forward compatible implementations.
type UnimplementedKGSServiceServer struct {
}

func (*UnimplementedKGSServiceServer) GetFreeGoTinyURL(ctx context.Context, req *KGSRequest) (*KGSResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFreeGoTinyURL not implemented")
}

func RegisterKGSServiceServer(s *grpc.Server, srv KGSServiceServer) {
	s.RegisterService(&_KGSService_serviceDesc, srv)
}

func _KGSService_GetFreeGoTinyURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KGSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KGSServiceServer).GetFreeGoTinyURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.KGSService/GetFreeGoTinyURL",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KGSServiceServer).GetFreeGoTinyURL(ctx, req.(*KGSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _KGSService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.KGSService",
	HandlerType: (*KGSServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFreeGoTinyURL",
			Handler:    _KGSService_GetFreeGoTinyURL_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kgs.proto",
}
